### ISSUE TITLE
请问你用的什么数据集？

### ISSUE THREAD

**Issue by ARnnn** [shinianzhihou/ChangeDetection#1]

**Comment by ARnnn** [comment]
可以分享一下数据集吗？

**Comment by shinianzhihou** [comment]
是两个开源数据集，Tiszadob 和 Szada ~

**Comment by ARnnn** [comment]
可以分享一下百度云吗

**Comment by ARnnn** [comment]
我下载不下来，能分享一下你的吗？

**Comment by ARnnn** [comment]
请问你在执行utils.py时已经把图片都切成112*1122的小图了吗？

**Comment by shinianzhihou** [comment]
是的，是先分割为112*112并且校正过后，才作为训练集进行训练

**Comment by shinianzhihou** [comment]
链接：https://pan.baidu.com/s/1egLpDOkvphLL-7pVr4FF3Q 
提取码：atkz 
这是我从官网下下来的数据集（未处理的）百度网盘的链接~

**Comment by ARnnn** [comment]
你是做了什么校正了，然后你是取的训练了1000轮的结果吗，不会过拟合吗

**Comment by ARnnn** [comment]
你那个测试的代码在哪啊，test里面没有测试的代码啊

**Comment by shinianzhihou** [comment]
1. 我只是尝试去复现了一下实验室师兄的代码
2. 直方图校正
3. 代码我还没有更新，原本打算在test里面的，但是觉得太麻烦了，就直接在train里面写了
4. 现在正在做相关损失函数的尝试，跑通的是直接内置的BCELoss

**Comment by Yyuanzeng** [comment]
> 的训练了1000轮的结果吗

你好，能否加一下QQ，一起讨论下变化检测

**Comment by Yyuanzeng** [comment]
> 你是做了什么校正了，然后你是取的训练了1000轮的结果吗，不会过拟合吗

QQ651570714

**Comment by Yyuanzeng** [comment]
> 是两个开源数据集，Tiszadob 和 Szada ~

能否参考一下裁剪好的数据呢

**Comment by AngieNikki** [comment]
我使用了直方图校正，但是跑出的结果跟您展示的差异较大，不知道您使用的是哪种直方图校正方法，可否共享一下代码～？
