### ISSUE TITLE
测试结果“PCC”的含义&测试结果可视化中输出图像的命名

### ISSUE THREAD

**Issue by taochx** [shinianzhihou/ChangeDetection#12]
按照您的模型代码以及详细的提示，已经可以比较好的进行复现，非常感谢您的分享。我有两个小的问题，请您解答：
     
      1.测试结果 logs/eval.csv中的“PCC”这个参数代表什么意思？
     2.测试结果可视化：
                                  第一个为输出结果，第二个为Ground-Truth
                   
                输出结果的名字可否根据test原文件名进行命名？否则不容易找到无法与Ground-Truth进行对比。

期待您的解答！非常感谢！

另外如果可以的话，请补充predict

**Comment by shinianzhihou** [comment]
1. PCC 就是 指 OA，有的变检文章里用这个表示 OA。OA=(TP+TN)/(TP+TN+FP+FN)。关于metric的实现细节，可以参考下`utils/metric.py`中的实现。
2. 这个当然可以，有两种思路，一种是读取数据时（__getitem__）把图片名字也返回，然后保存图片的时候，就可以把名字也保存下来。另外一种方法就是单独写一个 inference.py，在里面实现。这同时也能实现你说的 predict 的需求。
3. 关于增加 predict 的内容，最近可能没有时间，因为要忙着一个比赛和课程内容，可能之后会实现，到时候会@你~

（最后，感谢你的认可~欢迎star和pr~）
