### ISSUE TITLE
数据集格式

### ISSUE THREAD

**Issue by so-bright** [shinianzhihou/ChangeDetection#15]
请问，具体的数据集格式是什么样的呢？谢谢

**Comment by shinianzhihou** [comment]
抱歉，这个分支好久没看了，可以参考下这个文件～

`https://github.com/shinianzhihou/ChangeDetection/blob/master/work_dirs/cd_stb/meta_files/train.6.txt`

三列，分别是两个时相图片+标注图片，中间用`\t`分割，也可以用其他分割，但需要修改一些代码，可以参考`config`中的`sep='\t'`进行修改
