### ISSUE TITLE
为什么遥感变化检测的类别是2？这个2是怎么规定的呢

### ISSUE THREAD

**Issue by AllesOderNicht** [shinianzhihou/ChangeDetection#16]
为什么遥感变化检测的类别是2？这个2是怎么规定的呢

**Comment by shinianzhihou** [comment]
变化检测按照变化的层次可以分为两种，一种是基础的，比较粗粒度的 二值变化检测(binary change detection, BCD)，每个像素上的1/0分别表示该像素是/否为变化像素点；还有一种是细粒度高于BCD的变化检测，常见的有三类别（0/1/2表示无/减少/增加）和N类别（$X_1$类别变为$Y_1$类别，$X_n$类别变为$Y_n$类别。

BCD常见也常用，所以一般（我）默认为2。

实际上类比语义分割，只要把变化的类别当作分割的类别，多少种类别都可以。

**Comment by AllesOderNicht** [comment]
非常感谢您的回答，还有一个问题可以请您回答下吗。我发布在了另一个Issues里
