### ISSUE TITLE
性能分析

### ISSUE THREAD

**Issue by AllesOderNicht** [shinianzhihou/ChangeDetection#17]
我在使用您的源代码cdp.Unet模型跑LEVIR-CD数据集时，max_score达到了0.896.这个分数是不是指f1score呢。是不是可以将其理解为其他变化检测论文里的f1score。
如果是的话我可不可以将logs里的Precision和Recall也当成这个指标。。。

**Comment by shinianzhihou** [comment]
1) “源代码cdp.Unet”是指reaearch分支下的train.py吗？那里的max_score是一个字典，最大得分是在验证过程中的对应k的最大得分。

2) “是不是可以将其理解为其他变化检测论文里的f1score”，我理解是可以的（事实上，还需要多次试验取平均），我的计算方法是把所有的像素的t/f p/n 算出来，最终算指标，你可以参考metric脚本。

3) “如果是的话我可不可以将logs里的Precision和Recall也当成这个指标。。。” 如果你想看p和r的最大指标可以在记录里加上就行。

4) 实际上，很多变化检测的论文的指标不如简单的融合+分割，并且比赛中用的大多数都不是变化检测的“SOTA”方法，这也是开源这个repo的理由之一。

希望1)2)3)能帮助你，4)没有依据，纯粹个人看法。

**Comment by AllesOderNicht** [comment]
嗯嗯好谢谢

**Comment by AllesOderNicht** [comment]
您好，我还想问下，在使用unet做验证时（bs=1）我发现显存和训练保持一致，但是我在用STA或自己的算法做验证时，显存就会爆掉，再加入了eval()和with torch.no_grad()后也不起作用，不知道这是为什么

**Comment by shinianzhihou** [comment]
如果可以的话，把报错和部分代码一起展示出来会更好，个人感觉应该是算法模块的问题吧。

**Comment by AllesOderNicht** [comment]
发现问题了，测试的时候用了testmode但是这个没有裁剪尺寸，输入图像是1024，1024所以显存炸了， 感谢您的回答
