### ISSUE TITLE
请问gt图片是怎么处理的？

### ISSUE THREAD

**Issue by cx1011** [shinianzhihou/ChangeDetection#2]
直接切然后用来计算BCEloss会出现通道不匹配（output是单通道，gt3通道），我在切的时候将gt转化成单通道灰度图了，现在网络训练不收敛，感觉可能是我数据集处理有问题

**Comment by Yyuanzeng** [comment]
> 直接切然后用来计算BCEloss会出现通道不匹配（output是单通道，gt3通道），我在切的时候将gt转化成单通道灰度图了，现在网络训练不收敛，感觉可能是我数据集处理有问题

你好，我的数据处理部分也遇到问题了，能否加一下QQ讨论下651570714

**Comment by shinianzhihou** [comment]
我的理解是这样的：

- 关于输出通道问题，如果是单通道，最终结果需要自己做一下阈值分割

- 通道不匹配问题，gt三个通道基本都会一样的，写 datasets（nn.Module）的时候修改一下，只取gt的第一层就可以了

- 网络不收敛问题，因为分割的时候 Changed 和 Unchanged 比例不同，加上图片大小只有112，所以训练的时候直接用 BCELoss 会出现“收敛但是结果并不好，很多变化的被错误分为未变化的”的问题。所以有关损失函数问题我还在研究看看能不能找到好一点的损失函数。

- 关于图片如何分割的问题，可以用cv2进行直方图校正后直接进行 112*112 的分割。（因为分割好的图片是直接用的师兄的所以不方便直接给出来）

- 最后，因为我也在不断摸索前进过程中，所以会有一些问题，或者会给你带来一些误导，很抱歉。

**Comment by Rikaaaaaa95** [comment]
> 直接切然后用来计算BCEloss会出现通道不匹配（output是单通道，gt3通道），我在切的时候将gt转化成单通道灰度图了，现在网络训练不收敛，感觉可能是我数据集处理有问题

同学qq能不能留一下？

**Comment by Rikaaaaaa95** [comment]
> 直接切然后用来计算BCEloss会出现通道不匹配（output是单通道，gt3通道），我在切的时候将gt转化成单通道灰度图了，现在网络训练不收敛，感觉可能是我数据集处理有问题

我也遇到了这个问题，想请教一下你是怎么处理的

**Comment by Rikaaaaaa95** [comment]
> 直接切然后用来计算BCEloss会出现通道不匹配（output是单通道，gt3通道），我在切的时候将gt转化成单通道灰度图了，现在网络训练不收敛，感觉可能是我数据集处理有问题

同学你的qq能否留一下讨论一下
