### ISSUE TITLE
数据下载不下来 404

### ISSUE THREAD

**Issue by Larry-Zheng** [shinianzhihou/ChangeDetection#6]
兄嘚  你这个做得挺良心的 首先赞👍一个 
这个数据集貌似下载不下来 404 
我个人最近也在看变化检测相关方面 还想到一个不错的点子 用的OSCD dataset 训练的
方便加个qq 一起讨论一下吗 我qq 519334736

**Comment by shinianzhihou** [comment]
数据集你可以看一下 #5 ，我还没有更新readme的链接，没来得及弄这个，最近在忙着做毕设，可能之后有时间可以一起交流进步~
