### ISSUE TITLE
about transforms

### ISSUE THREAD

**Issue by AngieNikki** [shinianzhihou/ChangeDetection#7]
I want to test the model with the datasets of 4 channels but I have problems when conducted the transforms.py . The model cannot compute data of 4 channels, can it?
Looking forward to your reply!

**Comment by shinianzhihou** [comment]
If you train the model with images of 4 channels, of course you can test the model with same input channels. The `solver/transforms.py` just provides apis for the dataloaders in `data/*` and it has no relation with the channels. If you want to train the model with images of 4 channels, you can change the `BUILD.MODEL.IN_CHANNEL` in your configs.
![image](https://user-images.githubusercontent.com/29772895/81531722-d15a7d00-9395-11ea-91b5-eace6e935dc2.png)
